#define SETBIT(WORD,BITPOS) (WORD|=1<<BITPOS)
#define SSETBIT(WORD,BITPOS) (WORD=1<<BITPOS)
#define CLRBIT(WORD,BITPOS) (WORD&=~(1<<BITPOS))
#define SCLRBIT(WORD,BITPOS) (WORD=1<<BITPOS)
#define CPLBIT(WORD,BITPOS) (WORD^=1<<BITPOS)
#define READBIT(WORD,BITPOS) ((WORD>>BITPOS)&1)

#define WRITEBYTE(WORD,SETBITPOS,BYTE)  (WORD=(WORD&~(255<<SETBITPOS)) |(BYTE<<SETBITPOS))
#define WRITENIBBLE(WORD,SETBITPOS,NIBBLE)  (WORD=(WORD&~(15<<SETBITPOS)) |(NIBBLE<<SETBITPOS))
#define WRITEBIT(WORD,SETBITPOS,BIT) (WORD=(WORD&~(1<<SETBITPOS)) | (BIT<<SETBITPOS))

